/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_quadrature_demod_cf.h) */
/* BINDTOOL_HEADER_FILE_HASH(450dc397766c7b23cd8d7bfd4f132759)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pdu_utils/pdu_quadrature_demod_cf.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_quadrature_demod_cf_pydoc.h>

void bind_pdu_quadrature_demod_cf(py::module& m)
{

    using pdu_quadrature_demod_cf = ::gr::pdu_utils::pdu_quadrature_demod_cf;


    py::class_<pdu_quadrature_demod_cf,
               gr::block,
               gr::basic_block,
               std::shared_ptr<pdu_quadrature_demod_cf>>(
        m, "pdu_quadrature_demod_cf", D(pdu_quadrature_demod_cf))

        .def(py::init(&pdu_quadrature_demod_cf::make),
             py::arg("sensitivity"),
             D(pdu_quadrature_demod_cf, make))


        ;
}
