/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_burst_combiner.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c067a247112e206cdbd524fb59017ff4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pdu_utils/pdu_burst_combiner.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_burst_combiner_pydoc.h>

void bind_pdu_burst_combiner(py::module& m)
{

    using pdu_burst_combiner = ::gr::pdu_utils::pdu_burst_combiner;


    py::class_<pdu_burst_combiner,
               gr::block,
               gr::basic_block,
               std::shared_ptr<pdu_burst_combiner>>(
        m, "pdu_burst_combiner", D(pdu_burst_combiner))

        .def(py::init(&pdu_burst_combiner::make), D(pdu_burst_combiner, make))


        ;
}
