/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_align.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c7ced7ebeb770430529aa8fc63ad5983)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pdu_utils/pdu_align.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_align_pydoc.h>

void bind_pdu_align(py::module& m)
{

    using pdu_align = ::gr::pdu_utils::pdu_align;


    py::class_<pdu_align, gr::block, gr::basic_block, std::shared_ptr<pdu_align>>(
        m, "pdu_align", D(pdu_align))

        .def(py::init(&pdu_align::make),
             py::arg("syncwords"),
             py::arg("threshold"),
             py::arg("offset"),
             py::arg("mode") = ::gr::pdu_utils::align_modes::ALIGN_DROP,
             py::arg("match_mode") = ::gr::pdu_utils::align_match_mode::ALIGN_FIRST_MATCH,
             D(pdu_align, make))


        ;
}
