/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(upsample.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d17e5f439d282ee9df7cbdddd7e5e433)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pdu_utils/upsample.h>
// pydoc.h is automatically generated in the build directory
#include <upsample_pydoc.h>

void bind_upsample(py::module& m)
{

    using upsample = ::gr::pdu_utils::upsample;


    py::class_<upsample, gr::block, gr::basic_block, std::shared_ptr<upsample>>(
        m, "upsample", D(upsample))

        .def(
            py::init(&upsample::make), py::arg("n"), py::arg("repeat"), D(upsample, make))


        .def("set_n", &upsample::set_n, py::arg("n"), D(upsample, set_n))


        .def("set_repeat",
             &upsample::set_repeat,
             py::arg("repeat"),
             D(upsample, set_repeat))

        ;
}
