/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_downsample.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(113ad03fbfb3700d13d7a058dbf78371)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <pdu_utils/pdu_downsample.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_downsample_pydoc.h>

void bind_pdu_downsample(py::module& m)
{

    using pdu_downsample = ::gr::pdu_utils::pdu_downsample;


    py::class_<pdu_downsample,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<pdu_downsample>>(m, "pdu_downsample", D(pdu_downsample))

        .def(py::init(&pdu_downsample::make),
             py::arg("decimation"),
             py::arg("phase"),
             D(pdu_downsample, make))


        ;
}
