/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_complex_to_mag2.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2d6148cc41c7496e46cd1b8e5b6ae422)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <pdu_utils/pdu_complex_to_mag2.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_complex_to_mag2_pydoc.h>

void bind_pdu_complex_to_mag2(py::module& m)
{

    using pdu_complex_to_mag2 = ::gr::pdu_utils::pdu_complex_to_mag2;


    py::class_<pdu_complex_to_mag2,
               gr::block,
               gr::basic_block,
               std::shared_ptr<pdu_complex_to_mag2>>(
        m, "pdu_complex_to_mag2", D(pdu_complex_to_mag2))

        .def(py::init(&pdu_complex_to_mag2::make), D(pdu_complex_to_mag2, make))


        ;
}
