/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_range_filter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(85e297031e4b75a328d058c2466659d7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <pdu_utils/pdu_range_filter.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_range_filter_pydoc.h>

void bind_pdu_range_filter(py::module& m)
{

    using pdu_range_filter = ::gr::pdu_utils::pdu_range_filter;


    py::class_<pdu_range_filter,
               gr::block,
               gr::basic_block,
               std::shared_ptr<pdu_range_filter>>(
        m, "pdu_range_filter", D(pdu_range_filter))

        .def(py::init(&pdu_range_filter::make),
             py::arg("key"),
             py::arg("min"),
             py::arg("max"),
             py::arg("invert"),
             D(pdu_range_filter, make))


        ;
}
